package database

const (
	ColUsers         = "users"
	ColDomains       = "domains"
	ColSubdomains    = "subdomains"
	ColAliases       = "domain_aliases"
	ColRedirects     = "domain_redirects"
	ColApps          = "apps"
	ColDeployments   = "deployments"
	ColDatabases     = "databases"
	ColDBUsers       = "database_users"
	ColMailboxes     = "mailboxes"
	ColForwarders    = "email_forwarders"
	ColAutoresponders = "email_autoresponders"
	ColDNSZones      = "dns_zones"
	ColDNSRecords    = "dns_records"
	ColSSLCerts      = "ssl_certificates"
	ColBackups       = "backups"
	ColBackupSchedules = "backup_schedules"
	ColWordPress     = "wordpress_installs"
	ColFirewallRules = "firewall_rules"
	ColBlockedIPs    = "blocked_ips"
	ColCronJobs      = "cron_jobs"
	ColCronHistory   = "cron_history"
	ColSSHKeys       = "ssh_keys"
	ColNotifications = "notifications"
	ColWebhooks      = "webhooks"
	ColAuditLogs     = "audit_logs"
	ColServerConfig  = "server_config"
	ColGitHubDeploys = "github_deploys"
	ColDeployKeys    = "deploy_api_keys"
	ColMetrics       = "metrics"
)
