package database

const (
	ColUsers        = "mail_users"
	ColAccounts     = "mail_accounts"
	ColDevices      = "mail_devices"
	ColSignatures   = "mail_signatures"
	ColForwarders   = "mail_forwarders"
	ColFilters      = "mail_filters"
	ColThreadsIdx   = "mail_threads_idx"
	ColMessagesIdx  = "mail_messages_idx"
	ColPasskeys     = "mail_passkeys"
	ColOAuthClients = "mail_oauth_clients"
	ColOAuthGrants  = "mail_oauth_grants"
	ColOAuthTokens  = "mail_oauth_tokens"
	ColRefreshToks  = "mail_refresh_tokens"
	ColAudit        = "mail_audit"
	ColDrafts        = "mail_drafts"
	ColSent          = "mail_sent"
	ColTracking      = "mail_tracking_events"
	ColContacts          = "mail_contacts"
	ColContactGroups     = "mail_contact_groups"
	ColCampaigns          = "mail_campaigns"
	ColCampaignRecipients = "mail_campaign_recipients"
	ColCampaignTemplates  = "mail_campaign_templates"
	ColHeaderCache        = "mail_header_cache"
)
