// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwUs3NlcA1XThmpwLVB2MDTCcu3Duc9s',
    appId: '1:394156908079:android:a030388b335f37d77230da',
    messagingSenderId: '394156908079',
    projectId: 'betazen-server-panel',
    storageBucket: 'betazen-server-panel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjGwzjSuiVhuoSaC018bEQJJn4SCJspjo',
    appId: '1:394156908079:ios:de88c806c92bf2a97230da',
    messagingSenderId: '394156908079',
    projectId: 'betazen-server-panel',
    storageBucket: 'betazen-server-panel.firebasestorage.app',
    iosBundleId: 'com.betazeninfotech.betazenMail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjGwzjSuiVhuoSaC018bEQJJn4SCJspjo',
    appId: '1:394156908079:ios:de88c806c92bf2a97230da',
    messagingSenderId: '394156908079',
    projectId: 'betazen-server-panel',
    storageBucket: 'betazen-server-panel.firebasestorage.app',
    iosBundleId: 'com.betazeninfotech.betazenMail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEh7FQj3GyRi7KSYjwonPF37JgSYsbBDE',
    appId: '1:394156908079:web:98639f3500f533c37230da',
    messagingSenderId: '394156908079',
    projectId: 'betazen-server-panel',
    authDomain: 'betazen-server-panel.firebaseapp.com',
    storageBucket: 'betazen-server-panel.firebasestorage.app',
    measurementId: 'G-FVHKG7FPL1',
  );
}
