package agent

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"
)

// RunCommandLong runs a command with a custom timeout for long-running operations.
func RunCommandLong(ctx context.Context, timeout time.Duration, name string, args ...string) (*CommandResult, error) {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	return RunCommand(ctx, name, args...)
}

// UpdatePackageLists runs apt-get update.
func UpdatePackageLists(ctx context.Context) (string, error) {
	result, err := RunCommandLong(ctx, 10*time.Minute, "apt-get", "update", "-y")
	if err != nil {
		return "", fmt.Errorf("apt-get update failed: %w", err)
	}
	return result.Output, nil
}

// InstallPostfix installs and configures Postfix MTA.
func InstallPostfix(ctx context.Context, hostname, domain string) (string, error) {
	// Pre-seed debconf to avoid interactive prompts
	preseed := fmt.Sprintf(
		"postfix postfix/main_mailer_type select Internet Site\npostfix postfix/mailname string %s\n",
		hostname,
	)
	if err := os.WriteFile("/tmp/postfix-preseed.txt", []byte(preseed), 0644); err != nil {
		return "", fmt.Errorf("failed to write preseed: %w", err)
	}
	RunCommand(ctx, "debconf-set-selections", "/tmp/postfix-preseed.txt")

	// Install postfix
	result, err := RunCommandLong(ctx, 10*time.Minute, "bash", "-c",
		"DEBIAN_FRONTEND=noninteractive apt-get install -y postfix")
	if err != nil {
		return "", fmt.Errorf("failed to install postfix: %w", err)
	}

	// Create vmail user and directories
	RunCommand(ctx, "groupadd", "-g", "5000", "vmail")
	RunCommand(ctx, "useradd", "-g", "vmail", "-u", "5000", "vmail", "-d", "/var/mail/vhosts", "-s", "/usr/sbin/nologin")
	os.MkdirAll("/var/mail/vhosts/"+domain, 0770)
	RunCommand(ctx, "chown", "-R", "vmail:vmail", "/var/mail/vhosts")

	// Write main.cf
	mainCf := generatePostfixMainCf(hostname, domain)
	if err := os.WriteFile("/etc/postfix/main.cf", []byte(mainCf), 0644); err != nil {
		return "", fmt.Errorf("failed to write main.cf: %w", err)
	}

	// Create virtual mailbox map files
	os.WriteFile("/etc/postfix/virtual_mailbox_domains", []byte(domain+"\n"), 0644)
	os.WriteFile("/etc/postfix/virtual_mailbox_maps", []byte(""), 0644)
	RunCommand(ctx, "postmap", "/etc/postfix/virtual_mailbox_domains")
	RunCommand(ctx, "postmap", "/etc/postfix/virtual_mailbox_maps")

	return "Postfix installed and configured\n" + result.Output, nil
}

// InstallDovecot installs Dovecot IMAP/POP3 with virtual mailbox support.
func InstallDovecot(ctx context.Context, domain string) (string, error) {
	result, err := RunCommandLong(ctx, 10*time.Minute, "bash", "-c",
		"DEBIAN_FRONTEND=noninteractive apt-get install -y dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd")
	if err != nil {
		return "", fmt.Errorf("failed to install dovecot: %w", err)
	}
	return "Dovecot packages installed\n" + result.Output, nil
}

// ConfigurePostfixMasterCf configures submission and smtps ports in master.cf.
func ConfigurePostfixMasterCf(ctx context.Context) (string, error) {
	masterCfAdditions := `
# Submission port (587)
submission inet n       -       y       -       -       smtpd
  -o syslog_name=postfix/submission
  -o smtpd_tls_security_level=encrypt
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_tls_auth_only=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING

# SMTPS port (465)
smtps     inet  n       -       y       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes
  -o smtpd_sasl_auth_enable=yes
  -o smtpd_reject_unlisted_recipient=no
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject
  -o milter_macro_daemon_name=ORIGINATING
`
	// Read existing master.cf
	existing, err := os.ReadFile("/etc/postfix/master.cf")
	if err != nil {
		return "", fmt.Errorf("failed to read master.cf: %w", err)
	}

	// Append submission/smtps if not already present
	content := string(existing)
	if !strings.Contains(content, "submission inet") {
		content += masterCfAdditions
		if err := os.WriteFile("/etc/postfix/master.cf", []byte(content), 0644); err != nil {
			return "", fmt.Errorf("failed to write master.cf: %w", err)
		}
	}

	return "Postfix master.cf configured with submission/smtps ports", nil
}

// ConfigureDovecot configures Dovecot for virtual mailbox authentication and LMTP.
func ConfigureDovecot(ctx context.Context, domain string) (string, error) {
	// 10-auth.conf - disable system auth, enable passwd-file
	authConf := `# Dovecot authentication config - generated by ServerPanel
disable_plaintext_auth = yes
auth_mechanisms = plain login

!include auth-passwdfile.conf.ext
`
	os.WriteFile("/etc/dovecot/conf.d/10-auth.conf", []byte(authConf), 0644)

	// auth-passwdfile.conf.ext - password file auth
	passwdFileConf := `passdb {
  driver = passwd-file
  args = scheme=BLF-CRYPT username_format=%u /etc/dovecot/users
}

userdb {
  driver = static
  args = uid=vmail gid=vmail home=/var/mail/vhosts/%d/%n
}
`
	os.WriteFile("/etc/dovecot/conf.d/auth-passwdfile.conf.ext", []byte(passwdFileConf), 0644)

	// Create empty users file
	os.WriteFile("/etc/dovecot/users", []byte(""), 0644)
	RunCommand(ctx, "chown", "dovecot:dovecot", "/etc/dovecot/users")
	RunCommand(ctx, "chmod", "640", "/etc/dovecot/users")

	// 10-mail.conf - virtual mailbox location
	mailConf := `# Dovecot mail config - generated by ServerPanel
mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir
mail_privileged_group = vmail

namespace inbox {
  inbox = yes
}
`
	os.WriteFile("/etc/dovecot/conf.d/10-mail.conf", []byte(mailConf), 0644)

	// 10-master.conf - LMTP socket and auth socket for Postfix
	masterConf := `# Dovecot master config - generated by ServerPanel
service imap-login {
  inet_listener imap {
    port = 0
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

service pop3-login {
  inet_listener pop3 {
    port = 0
  }
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0600
    user = postfix
    group = postfix
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
  unix_listener auth-userdb {
    mode = 0600
    user = vmail
  }
  user = dovecot
}

service auth-worker {
  user = vmail
}
`
	os.WriteFile("/etc/dovecot/conf.d/10-master.conf", []byte(masterConf), 0644)

	// 10-ssl.conf - SSL settings
	sslConf := `# Dovecot SSL config - generated by ServerPanel
ssl = required
ssl_cert = </etc/ssl/certs/ssl-cert-snakeoil.pem
ssl_key = </etc/ssl/private/ssl-cert-snakeoil.key
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
`
	os.WriteFile("/etc/dovecot/conf.d/10-ssl.conf", []byte(sslConf), 0644)

	return "Dovecot configured for virtual mailboxes with LMTP and auth sockets", nil
}

// InstallSpamAssassin installs and enables SpamAssassin.
func InstallSpamAssassin(ctx context.Context) (string, error) {
	result, err := RunCommandLong(ctx, 10*time.Minute, "bash", "-c",
		"DEBIAN_FRONTEND=noninteractive apt-get install -y spamassassin spamc")
	if err != nil {
		return "", fmt.Errorf("failed to install spamassassin: %w", err)
	}

	// Configure local.cf
	localCf := `# SpamAssassin config - generated by ServerPanel
required_score 5.0
report_safe 0
rewrite_header Subject [SPAM]
use_bayes 1
bayes_auto_learn 1
`
	os.WriteFile("/etc/spamassassin/local.cf", []byte(localCf), 0644)

	ServiceAction(ctx, "spamassassin", "enable")
	ServiceAction(ctx, "spamassassin", "start")

	return "SpamAssassin installed and enabled\n" + result.Output, nil
}

// InstallOpenDKIM installs OpenDKIM and generates keys for the domain.
func InstallOpenDKIM(ctx context.Context, domain string) (string, error) {
	result, err := RunCommandLong(ctx, 10*time.Minute, "bash", "-c",
		"DEBIAN_FRONTEND=noninteractive apt-get install -y opendkim opendkim-tools")
	if err != nil {
		return "", fmt.Errorf("failed to install opendkim: %w", err)
	}

	// Create directories
	os.MkdirAll("/etc/opendkim/keys/"+domain, 0750)

	// Generate DKIM key
	RunCommand(ctx, "opendkim-genkey", "-b", "2048", "-d", domain, "-D", "/etc/opendkim/keys/"+domain, "-s", "mail", "-v")
	RunCommand(ctx, "chown", "-R", "opendkim:opendkim", "/etc/opendkim")

	// Write opendkim.conf
	opendkimConf := fmt.Sprintf(`# OpenDKIM config - generated by ServerPanel
AutoRestart             Yes
AutoRestartRate         10/1h
Syslog                  yes
SyslogSuccess           Yes
LogWhy                  Yes
Canonicalization        relaxed/simple
ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts
KeyTable                refile:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
Mode                    sv
PidFile                 /var/run/opendkim/opendkim.pid
SignatureAlgorithm      rsa-sha256
UserID                  opendkim:opendkim
Socket                  inet:12301@localhost
`)
	os.WriteFile("/etc/opendkim.conf", []byte(opendkimConf), 0644)

	// TrustedHosts
	trustedHosts := fmt.Sprintf("127.0.0.1\nlocalhost\n%s\n*.%s\n", domain, domain)
	os.WriteFile("/etc/opendkim/TrustedHosts", []byte(trustedHosts), 0644)

	// KeyTable
	keyTable := fmt.Sprintf("mail._domainkey.%s %s:mail:/etc/opendkim/keys/%s/mail.private\n", domain, domain, domain)
	os.WriteFile("/etc/opendkim/KeyTable", []byte(keyTable), 0644)

	// SigningTable
	signingTable := fmt.Sprintf("*@%s mail._domainkey.%s\n", domain, domain)
	os.WriteFile("/etc/opendkim/SigningTable", []byte(signingTable), 0644)

	// Add milter to Postfix
	RunCommand(ctx, "bash", "-c", `postconf -e "milter_protocol = 6"`)
	RunCommand(ctx, "bash", "-c", `postconf -e "milter_default_action = accept"`)
	RunCommand(ctx, "bash", "-c", `postconf -e "smtpd_milters = inet:localhost:12301"`)
	RunCommand(ctx, "bash", "-c", `postconf -e "non_smtpd_milters = inet:localhost:12301"`)

	ServiceAction(ctx, "opendkim", "enable")
	ServiceAction(ctx, "opendkim", "start")

	return "OpenDKIM installed with keys generated\n" + result.Output, nil
}

// InstallClamAV installs ClamAV antivirus daemon.
func InstallClamAV(ctx context.Context) (string, error) {
	result, err := RunCommandLong(ctx, 15*time.Minute, "bash", "-c",
		"DEBIAN_FRONTEND=noninteractive apt-get install -y clamav clamav-daemon")
	if err != nil {
		return "", fmt.Errorf("failed to install clamav: %w", err)
	}

	// Stop freshclam if running (to avoid lock conflict), update definitions, restart
	RunCommand(ctx, "systemctl", "stop", "clamav-freshclam")
	RunCommandLong(ctx, 10*time.Minute, "freshclam")
	ServiceAction(ctx, "clamav-freshclam", "enable")
	ServiceAction(ctx, "clamav-freshclam", "start")
	ServiceAction(ctx, "clamav-daemon", "enable")
	ServiceAction(ctx, "clamav-daemon", "start")

	return "ClamAV installed and virus definitions updated\n" + result.Output, nil
}

// OpenEmailFirewallPorts opens SMTP, submission, SMTPS, IMAPS, POP3S ports via UFW.
func OpenEmailFirewallPorts(ctx context.Context) (string, error) {
	ports := []string{"25/tcp", "465/tcp", "587/tcp", "993/tcp", "995/tcp"}
	var outputs []string
	for _, p := range ports {
		result, _ := RunCommand(ctx, "ufw", "allow", p)
		if result != nil {
			outputs = append(outputs, result.Output)
		}
	}
	return fmt.Sprintf("Opened firewall ports: %s\n%s", strings.Join(ports, ", "), strings.Join(outputs, "\n")), nil
}

// EnableEmailServices enables and starts all configured email services.
func EnableEmailServices(ctx context.Context, spamassassin, opendkim, clamav bool) (string, error) {
	services := []string{"postfix", "dovecot"}
	if spamassassin {
		services = append(services, "spamassassin")
	}
	if opendkim {
		services = append(services, "opendkim")
	}
	if clamav {
		services = append(services, "clamav-daemon", "clamav-freshclam")
	}

	var outputs []string
	for _, svc := range services {
		ServiceAction(ctx, svc, "enable")
		ServiceAction(ctx, svc, "restart")
		outputs = append(outputs, fmt.Sprintf("  %s: enabled and restarted", svc))
	}

	return fmt.Sprintf("Services started:\n%s", strings.Join(outputs, "\n")), nil
}

// VerifyEmailServices checks that all expected services are running.
func VerifyEmailServices(ctx context.Context, spamassassin, opendkim, clamav bool) (string, error) {
	services := []string{"postfix", "dovecot"}
	if spamassassin {
		services = append(services, "spamassassin")
	}
	if opendkim {
		services = append(services, "opendkim")
	}
	if clamav {
		services = append(services, "clamav-daemon")
	}

	var outputs []string
	var failedServices []string
	for _, svc := range services {
		result, err := RunCommand(ctx, "systemctl", "is-active", svc)
		status := "inactive"
		if err == nil && result != nil {
			status = strings.TrimSpace(result.Output)
		}
		outputs = append(outputs, fmt.Sprintf("  %s: %s", svc, status))
		if status != "active" {
			failedServices = append(failedServices, svc)
		}
	}

	output := strings.Join(outputs, "\n")
	if len(failedServices) > 0 {
		return output, fmt.Errorf("services not running: %s", strings.Join(failedServices, ", "))
	}

	return "All services verified running:\n" + output, nil
}

// CheckEmailServiceStatus returns whether a specific service is installed, running, and its version.
func CheckEmailServiceStatus(ctx context.Context, service, pkg string) (installed bool, running bool, version string) {
	// Check if running
	result, err := RunCommand(ctx, "systemctl", "is-active", service)
	if err == nil && result != nil && strings.TrimSpace(result.Output) == "active" {
		running = true
	}

	// Check if installed and get version
	result, err = RunCommand(ctx, "dpkg-query", "-W", "-f=${Version}", pkg)
	if err == nil && result != nil && result.ExitCode == 0 {
		installed = true
		version = strings.TrimSpace(result.Output)
	}

	return
}

func generatePostfixMainCf(hostname, domain string) string {
	return fmt.Sprintf(`# Postfix main.cf - generated by ServerPanel
smtpd_banner = $myhostname ESMTP
biff = no
append_dot_mydomain = no
readme_directory = no
compatibility_level = 3.6

myhostname = %s
mydomain = %s
myorigin = $mydomain
mydestination = localhost
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
inet_interfaces = all
inet_protocols = all

# Virtual mailbox settings
virtual_mailbox_domains = hash:/etc/postfix/virtual_mailbox_domains
virtual_mailbox_maps = hash:/etc/postfix/virtual_mailbox_maps
virtual_mailbox_base = /var/mail/vhosts
virtual_uid_maps = static:5000
virtual_gid_maps = static:5000
virtual_transport = lmtp:unix:private/dovecot-lmtp

# TLS settings
smtpd_tls_security_level = may
smtpd_tls_cert_file = /etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file = /etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
smtp_tls_security_level = may
smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1

# SASL settings (Dovecot auth)
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination

# Limits
message_size_limit = 52428800
mailbox_size_limit = 0
`, hostname, domain)
}
