package agent

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// MailSuiteInstallOptions controls how InstallMailSuite provisions the
// mail-suite product on this server.
type MailSuiteInstallOptions struct {
	Domain        string // e.g. mail.example.com — used for the nginx vhost + Let's Encrypt cert
	MongoURI      string // Mongo connection string for the mail_suite DB
	MongoDBName   string // defaults to "mail_suite"
	PanelURL      string // Betazen panel URL the mail-suite backend will call for DNS
	PanelToken    string // token the mail-suite backend uses to authenticate to the panel
	JWTSecret     string // optional — generated if empty
	ServiceToken  string // optional — generated if empty (token the panel uses to call mail-suite)
	BinarySource  string // optional path to a prebuilt mail-suite binary; defaults to <repo>/mail-suite/backend (built in place)
	InstallDir    string // defaults to /opt/mail-suite
}

// MailSuiteInstallResult is what the caller registers in the panel.
type MailSuiteInstallResult struct {
	APIURL        string
	WebmailURL    string
	ServiceToken  string
	InstallDir    string
	BinaryPath    string
	SystemdUnit   string
	NginxVhost    string
}

// InstallMailSuite runs an idempotent provisioning sequence:
//
//   1. Create install dir.
//   2. Build (or copy) the mail-suite binary.
//   3. Write .env (auto-generating JWT_SECRET / SERVICE_TOKEN if blank).
//   4. Write the systemd unit and enable+start it.
//   5. Write an nginx vhost (mail-suite is reverse-proxied at /).
//   6. Provision a Let's Encrypt cert with certbot --nginx (best effort).
//
// Returns the public API URL + the service token the panel should store.
func InstallMailSuite(ctx context.Context, opts MailSuiteInstallOptions) (*MailSuiteInstallResult, error) {
	if strings.TrimSpace(opts.Domain) == "" {
		return nil, fmt.Errorf("domain required")
	}
	if opts.InstallDir == "" {
		opts.InstallDir = "/opt/mail-suite"
	}
	if opts.MongoDBName == "" {
		opts.MongoDBName = "mail_suite"
	}
	if opts.MongoURI == "" {
		opts.MongoURI = "mongodb://localhost:27017"
	}
	if opts.JWTSecret == "" {
		s, err := randomHex(32)
		if err != nil {
			return nil, fmt.Errorf("jwt secret: %w", err)
		}
		opts.JWTSecret = s
	}
	if opts.ServiceToken == "" {
		s, err := randomHex(32)
		if err != nil {
			return nil, fmt.Errorf("service token: %w", err)
		}
		opts.ServiceToken = s
	}

	binaryPath := filepath.Join(opts.InstallDir, "mail-suite")
	systemdUnit := "/etc/systemd/system/mail-suite.service"
	nginxVhost := "/etc/nginx/sites-available/mail-suite.conf"
	nginxLink := "/etc/nginx/sites-enabled/mail-suite.conf"
	envPath := filepath.Join(opts.InstallDir, ".env")

	// 1. dirs
	if err := os.MkdirAll(opts.InstallDir, 0750); err != nil {
		return nil, fmt.Errorf("mkdir %s: %w", opts.InstallDir, err)
	}

	// 2. binary
	if opts.BinarySource != "" {
		if _, err := RunCommand(ctx, "install", "-m", "0755", opts.BinarySource, binaryPath); err != nil {
			return nil, fmt.Errorf("install binary: %w", err)
		}
	} else {
		// Build from the in-repo source. The repo is expected to be at
		// /opt/server-panel/mail-suite/backend (the panel's standard
		// deploy layout); fall back to $PWD/mail-suite/backend for
		// dev installs.
		src := "/opt/server-panel/mail-suite/backend"
		if _, err := os.Stat(src); err != nil {
			cwd, _ := os.Getwd()
			alt := filepath.Join(cwd, "mail-suite", "backend")
			if _, err := os.Stat(alt); err == nil {
				src = alt
			}
		}
		// `go build` writes to opts.InstallDir/mail-suite directly.
		if _, err := RunCommandLong(ctx, 10*time.Minute, "bash", "-lc",
			fmt.Sprintf("cd %s && GOOS=linux GOARCH=amd64 go build -o %s ./cmd/server", shellQuote(src), shellQuote(binaryPath))); err != nil {
			return nil, fmt.Errorf("go build: %w", err)
		}
	}

	// 3. .env
	envBody := fmt.Sprintf(`# Auto-generated by Betazen panel — edit with care.
APP_ENV=production
LOG_LEVEL=info

MONGO_URI=%s
MONGO_DB=%s

JWT_SECRET=%s
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=168h

SERVER_PORT=9090
PUBLIC_URL=https://%s

IMAP_HOST=127.0.0.1
IMAP_PORT=143
SMTP_HOST=127.0.0.1
SMTP_PORT=587

BETAZEN_PANEL_URL=%s
BETAZEN_PANEL_TOKEN=%s

WEBAUTHN_RPID=%s
WEBAUTHN_RP_NAME=Betazen Mail
WEBAUTHN_ORIGINS=https://%s

OAUTH_ISSUER=https://%s

# Service token used by the Betazen panel to call this mail-suite
# backend's admin endpoints. The panel stores the same value when it
# registers the deployment.
PANEL_SERVICE_TOKEN=%s
`, opts.MongoURI, opts.MongoDBName, opts.JWTSecret,
		opts.Domain, opts.PanelURL, opts.PanelToken,
		opts.Domain, opts.Domain, opts.Domain, opts.ServiceToken)
	if err := os.WriteFile(envPath, []byte(envBody), 0640); err != nil {
		return nil, fmt.Errorf("write .env: %w", err)
	}

	// 4. systemd unit
	unit := fmt.Sprintf(`[Unit]
Description=Betazen Mail Suite
After=network.target mongod.service

[Service]
Type=simple
WorkingDirectory=%s
EnvironmentFile=%s
ExecStart=%s
Restart=on-failure
RestartSec=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
`, opts.InstallDir, envPath, binaryPath)
	if err := os.WriteFile(systemdUnit, []byte(unit), 0644); err != nil {
		return nil, fmt.Errorf("write systemd unit: %w", err)
	}
	RunCommand(ctx, "systemctl", "daemon-reload")
	if _, err := RunCommand(ctx, "systemctl", "enable", "--now", "mail-suite.service"); err != nil {
		return nil, fmt.Errorf("systemctl enable mail-suite: %w", err)
	}

	// 5. nginx vhost (reverse-proxy)
	vhost := fmt.Sprintf(`# Auto-generated by Betazen panel.
server {
    listen 80;
    server_name %s;

    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl http2;
    server_name %s;

    # Certbot fills these in; serve self-signed until then.
    ssl_certificate     /etc/letsencrypt/live/%s/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/%s/privkey.pem;

    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 5m;
    }
}
`, opts.Domain, opts.Domain, opts.Domain, opts.Domain)
	if err := os.WriteFile(nginxVhost, []byte(vhost), 0644); err != nil {
		return nil, fmt.Errorf("write nginx vhost: %w", err)
	}
	// idempotent symlink
	_ = os.Remove(nginxLink)
	_ = os.Symlink(nginxVhost, nginxLink)

	// 6. certbot (best-effort)
	_, _ = RunCommandLong(ctx, 5*time.Minute, "certbot", "--nginx",
		"-d", opts.Domain, "--non-interactive", "--agree-tos",
		"--register-unsafely-without-email", "--redirect")
	RunCommand(ctx, "nginx", "-t")
	RunCommand(ctx, "systemctl", "reload", "nginx")

	return &MailSuiteInstallResult{
		APIURL:       "https://" + opts.Domain,
		WebmailURL:   "https://" + opts.Domain + "/mail/",
		ServiceToken: opts.ServiceToken,
		InstallDir:   opts.InstallDir,
		BinaryPath:   binaryPath,
		SystemdUnit:  systemdUnit,
		NginxVhost:   nginxVhost,
	}, nil
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// shellQuote wraps a string for safe shell interpolation. Used in the
// `bash -lc` go-build invocation so install dirs with spaces don't
// break the build step.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
