package models

import (
	"time"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Mailbox struct {
	ID              primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	Email           string             `bson:"email" json:"email"`
	Password        string             `bson:"password" json:"-"`
	EncryptedPass   string             `bson:"encrypted_pass,omitempty" json:"-"`
	// LegacyEncryptedPass holds a SOURCE-server-sealed encrypted_pass blob
	// that a transfer could not re-key (source JWT_SECRET unreadable, or the
	// individual cipher failed to decrypt). The transfer parks it here rather
	// than destroying it, so webmail SSO can still be recovered later —
	// RekeyLegacyMailboxes re-seals it under this panel's key once the
	// operator supplies the old JWT_SECRET — instead of forcing a password
	// reset on every migrated mailbox. Never served over the API.
	LegacyEncryptedPass string `bson:"legacy_encrypted_pass,omitempty" json:"-"`
	// Password-reset provenance (v3.1.180). Stamped on every password (re)set
	// so the operator can audit which mailboxes had their webmail-SSO
	// credential re-seeded, when, and through which surface — in particular
	// which ones went through the public API vs the panel. `password_set_via`
	// is one of "panel" | "api" | "cli"; `password_set_by` is the acting
	// user's email or the API token's name (prefixed "api:").
	PasswordSetAt  *time.Time `bson:"password_set_at,omitempty" json:"password_set_at,omitempty"`
	PasswordSetVia string     `bson:"password_set_via,omitempty" json:"password_set_via,omitempty"`
	PasswordSetBy  string     `bson:"password_set_by,omitempty" json:"password_set_by,omitempty"`
	// SSOReady is DERIVED, never stored (bson:"-"): true when encrypted_pass
	// is present, i.e. the one-click "Open in Webmail" SSO will work. Lets an
	// API/UI consumer see at a glance which mailboxes still need a password
	// reset to re-enable SSO after a migration.
	SSOReady bool `bson:"-" json:"sso_ready"`
	Domain          string             `bson:"domain" json:"domain"`
	QuotaMB         int                `bson:"quota_mb" json:"quota_mb"`
	UsedMB          float64            `bson:"used_mb" json:"used_mb"`
	SendLimitPerHour int               `bson:"send_limit_per_hour" json:"send_limit_per_hour"`
	CreatedAt       time.Time          `bson:"created_at" json:"created_at"`
	UpdatedAt       time.Time          `bson:"updated_at" json:"updated_at"`
}

type CreateMailboxRequest struct {
	Email            string `json:"email" validate:"required,email"`
	Password         string `json:"password" validate:"required,min=8"`
	Domain           string `json:"domain" validate:"required"`
	QuotaMB          int    `json:"quota_mb"`
	SendLimitPerHour int    `json:"send_limit_per_hour"`
}

// ResetMailboxPasswordRequest is the body for the external programmatic
// password-reset endpoint POST /external/email/:domain/mailboxes/:addr/password.
// Matches CreateMailboxRequest's min=8 rule so the new password meets the
// same floor as the original; the doveadm SHA512-CRYPT hash and the
// AES-encrypted plaintext (used for webmail SSO) are regenerated by
// EmailService.UpdateMailbox.
type ResetMailboxPasswordRequest struct {
	// Optional as of v3.1.180: leave blank to have the server generate a
	// strong password and return it in the response (the webmail-SSO
	// recovery flow — a migration that couldn't re-key encrypted_pass leaves
	// a mailbox with no SSO credential, and only setting a fresh password
	// re-seeds it). When supplied it must still meet the min=8 floor.
	Password string `json:"password" validate:"omitempty,min=8"`
}

type EmailForwarder struct {
	ID           primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	Source       string             `bson:"source" json:"source"`
	Destinations []string           `bson:"destinations" json:"destinations"`
	KeepCopy     bool               `bson:"keep_copy" json:"keep_copy"`
	Domain       string             `bson:"domain" json:"domain"`
	CreatedAt    time.Time          `bson:"created_at" json:"created_at"`
}

type Autoresponder struct {
	ID            primitive.ObjectID `bson:"_id,omitempty" json:"id"`
	Email         string             `bson:"email" json:"email"`
	Subject       string             `bson:"subject" json:"subject"`
	Body          string             `bson:"body" json:"body"`
	StartDate     *time.Time         `bson:"start_date" json:"start_date"`
	EndDate       *time.Time         `bson:"end_date" json:"end_date"`
	IntervalHours int                `bson:"interval_hours" json:"interval_hours"`
	Domain        string             `bson:"domain" json:"domain"`
	CreatedAt     time.Time          `bson:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `bson:"updated_at" json:"updated_at"`
}

type SpamSettings struct {
	Domain        string   `bson:"domain" json:"domain"`
	SpamThreshold float64  `bson:"spam_threshold" json:"spam_threshold"`
	SpamAction    string   `bson:"spam_action" json:"spam_action"`
	Whitelist     []string `bson:"whitelist" json:"whitelist"`
	Blacklist     []string `bson:"blacklist" json:"blacklist"`
	ClamAVEnabled bool     `bson:"clamav_enabled" json:"clamav_enabled"`
}
